name: Embedded Build

on:
  push: {}
  pull_request: {}
    
jobs:

  build-windows:
    
    runs-on: windows-2019
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      shell: cmd
      run: git submodule update --init --recursive
      
    - name: Build Python
      shell: cmd
      run: |
        cd Scripts
        call BuildPythonForWindows.bat --ci
        cd ..
        mkdir cmake-build-release
        cd cmake-build-release
        cmake ..
        
    - name: Build DearPyGui
      shell: cmd
      run: |
        cmake --build cmake-build-release --config Release

  build-MacOS:
    
    runs-on: MacOS-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: git submodule update --init --recursive
    
    - name: Build Python
      run: |
        cd Dependencies/cpython
        mkdir debug
        cd debug
        ../configure --with-pydebug --enable-shared --prefix=$(pwd) LDFLAGS=-Wl,-rpath,$(pwd)
        make
        make install

    - name: Build DearPyGui
      run: |
        mkdir cmake-build-debug
        cd cmake-build-debug
        cmake ..
        cd ..
        cmake --build cmake-build-debug --config Debug

  build-Ubuntu:
    
    runs-on: ubuntu-18.04
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: git submodule update --init --recursive
    
    - name: Build Python
      run: |
        sudo apt-get update
        sudo apt-get install libgl1-mesa-dev
        sudo apt-get install xorg-dev
        cd Dependencies/cpython
        mkdir debug
        cd debug
        ../configure --with-pydebug --enable-shared
        make

    - name: Build DearPyGui
      run: |
        mkdir cmake-build-debug
        cd cmake-build-debug
        cmake ..
        cd ..
        cmake --build cmake-build-debug --config Debug
